services:
  - type: web
    name: postiz-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: postiz-redis
          property: connectionString
      - key: QUEUE_CONNECTION
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: CACHE_DRIVER
        value: redis
    # For Docker runtime, prefer CMD in Dockerfile.
    # If you must override here, use dockerCommand (NOT startCommand), e.g.:
    # dockerCommand: php artisan serve --host=0.0.0.0 --port=$PORT

  - type: worker
    name: postiz-queue
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: php artisan queue:work --sleep=1 --tries=3 --timeout=120   # ✅ use dockerCommand
    envVars:
      - key: APP_KEY
        fromService:
          type: web
          name: postiz-app
          envVarKey: APP_KEY
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: postiz-redis
          property: connectionString
      - key: QUEUE_CONNECTION
        value: redis

  - type: cron
    name: postiz-scheduler
    runtime: docker
    dockerfilePath: ./Dockerfile
    schedule: "* * * * *"
    dockerCommand: php artisan schedule:run                                  # ✅ use dockerCommand
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: postiz-redis
          property: connectionString

  - type: redis
    name: postiz-redis
    plan: free
    ipAllowList: []   # ✅ required: deny public access; internal services still connect

databases:
  - name: postiz-db
    plan: free
