services:
  - type: web
    name: postiz-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}      # no extra https://
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: internalConnectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: postiz-redis
          property: internalConnectionString
      - key: QUEUE_CONNECTION
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: CACHE_DRIVER
        value: redis
    # If you don't set CMD in Dockerfile, uncomment one of these:
    # startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    # OR use nginx+php-fpm in Dockerfile listening on $PORT

  - type: worker
    name: postiz-queue
    runtime: docker
    dockerfilePath: ./Dockerfile
    startCommand: php artisan queue:work --sleep=1 --tries=3 --timeout=120
    envVars:
      - key: APP_KEY
        fromService: { type: web, name: postiz-app, envVarKey: APP_KEY }  # reuse same key
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase: { name: postiz-db, property: internalConnectionString }
      - key: REDIS_URL
        fromService: { type: redis, name: postiz-redis, property: internalConnectionString }
      - key: QUEUE_CONNECTION
        value: redis

  - type: cron
    name: postiz-scheduler
    runtime: docker
    dockerfilePath: ./Dockerfile
    schedule: "* * * * *"   # every minute
    startCommand: php artisan schedule:run
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase: { name: postiz-db, property: internalConnectionString }
      - key: REDIS_URL
        fromService: { type: redis, name: postiz-redis, property: internalConnectionString }

  - type: redis
    name: postiz-redis
    plan: free

databases:
  - name: postiz-db
    plan: free
